### PR TITLE
Added NL locale, also added tests for locale

### LINKED ISSUE #13: Support for Dutch language
To support Dutch language (which is 'nl'), add the following please ^^

```
<?php

return [
    'message' => 'Is de e-mail niet goed leesbaar?',
    'link'    => 'Bekijk het in de browser',
];

### PR DESCRIPTION
**Pull request by Sammyjo20**
This PR adds the Dutch translations for Wagonwheel. 

I have also included some basic locale tests to make sure these are being pulled in correctly.

@ryangjchandler or @Jhnbrn90 do you guys mind having a quick look over the tests I have created please? (If you get a moment) I'm still **relatively** new to testing and not sure if I've done it the best way possible!

### CODE REVIEW

**Comment by ryangjchandler** [comment]
Seem pretty solid to me. Assuming the tests pass that is 😉

I'd say use `require` instead of `include` though since `require` throws a fatal error when it fails, seems a bit safer.

**Comment by ryangjchandler** [comment]
On second thought, this could be a nice use case for a dataset, so a single test is run for each item in the dataset. 

Good blog post from Tighten here: https://tighten.co/blog/tidying-up-your-phpunit-tests-with-data-providers/

Would mean that any new translations added would need to meet the test requirements, also means that any new keys only need to be added to a single test method.

**Comment by Sammyjo20** [comment]
Booom! What do you think of the new tests? Thanks for sharing that, I had no idea you could do that! 😅 Seems like the test matrix doesn't want to work on some of the tests though.

**Comment by Jhnbrn90** [comment]
The PR looks good. I also tried solving the issue where the `--prefer-lowest` run within the tests matrix can't find the appropriate classes, but I couldn't find it yet. I'm afraid I don't have time this week to investigate this issue further. 
Do you have any idea @ryangjchandler ?

**Comment by Sammyjo20** [comment]
Is `prefer-lowest` standard? We could always remove it if people aren't going to use it. But It would be good to know why the tests are failing and if it's something we need to fix. It might just be a composer dependency version issue.

**Comment by Sammyjo20** [comment]
I'm going to merge this for now - as I think it's useful to have these tests in place, but I'm going to open an issue to fix these tests.

**Pull request merged**
