### PR TITLE
Allow php 8

### PR DESCRIPTION
**Pull request by michaelbonner**

### CODE REVIEW

**Comment by ryangjchandler** [comment]
@michaelbonner Any reason why you've changed it from `^7.3` to `^7.1`?

Laravel `^8.0` doesn't support PHP `<7.3`, so people running 7.1 wouldn't be able to use this package anyway.

**Comment by Sammyjo20** [comment]
Thanks for the PR @michaelbonner. Ryan is right, please could you change the PR to accept `^7.3 || 8.0` to allow support for Laravel 8? Thanks!

**Comment by michaelbonner** [comment]
I've updated that now. Thanks for pointing that out @ryangjchandler

**Comment by Sammyjo20** [comment]
I think `^8.0` is fine as that's what Laravel 8 uses as it's requirement, @ryangjchandler what do you think?

**Comment by ryangjchandler** [comment]
> I think `^8.0` is fine as that's what Laravel 8 uses as it's requirement, @ryangjchandler what do you think?

Yeah ^8.0 is what it should be.

**Comment by michaelbonner** [comment]
Cool, I just copied over what the Laravel 8.x branch has for the PHP requirement.

**Review by ryangjchandler — APPROVED** [review]

**Comment by michaelbonner** [comment]
Thanks for approving that @ryangjchandler. Is there anything I can do to help prepare a release for this?

**Comment by Sammyjo20** [comment]
@michaelbonner Apologies for the delay. Work has been very busy lately. I will merge this tonight!

**Comment by michaelbonner** [comment]
Thanks @Sammyjo20 
And thank you for building an awesome package!

**Pull request merged**
