### PR TITLE
Add Portuguese (Portugal) translation

### PR DESCRIPTION
**Pull request by joseborges**
Add Portuguese (Portugal) translation

### CODE REVIEW

**Comment by joseborges** [comment]
I'll be using this laravel package in my project, which has English (EN) and Portuguese (PT) language. Thanks for sharing._

**Comment by Sammyjo20** [comment]
Great, thanks @joseborges! 🔥

**Comment by joseborges** [comment]
Hi @Sammyjo20  could you please mark this repo as part of #hacktobefest? Thanks!

**Comment by Sammyjo20** [comment]
@joseborges Done!

**Pull request merged**
