### PR TITLE
Add GitHub Action workflow for CI

### PR DESCRIPTION
**Pull request by Jhnbrn90**
## What has been done
- Added GitHub workflow file to run `phpunit` for every push to master and every PR to the master branch.

This will ensure the test suite is green before merging new code.

## Todo
- @Sammyjo20, if you're open to add a codestyle checker as well I was thinking about using the `symplify/easy-coding-standard`. This codestyle would then also run as part of this GitHub Actions CI. We could also add a Git Hook to make sure newly comitted code adheres to the style and phpunit tests are passing. Let me know what you think that. If you like that idea, I can add that in a next PR.

### CODE REVIEW

**Comment by Sammyjo20** [comment]
Thanks @Jhnbrn90, you beat me to it! I was thinking of using the one that's on [Lasso](https://github.com/sammyjo20/lasso) if you don't have any objections? Feel free to change my mind though if symplify's offering is better.

**Comment by Sammyjo20** [comment]
This one https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by Jhnbrn90** [comment]
@Sammyjo20 Sure thing, I've used PHP CS Fixer now. Would you also like to use a matrix for unit testing like you have in lasso? https://github.com/Sammyjo20/Lasso/blob/master/.github/workflows/tests.yml

**Comment by Sammyjo20** [comment]
Thanks dude, yeah that would be incredible. I don't mind adding that in - would you be able to enable modification on this PR?

**Comment by Jhnbrn90** [comment]
@Sammyjo20 You should be able to add new commits to this branch 👍

**Comment by Sammyjo20** [comment]
Whoop, let's get these tests added. Thanks @Jhnbrn90 🤘

**Pull request merged**
